---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE}
library(tidyverse)
library(readr)
library(readxl)
library(plotly)
```



**Read in data**
```{r}
delays <- read_csv("Final Flights Data/Airline on-time perform(2015-2019).csv") 

```
```{r}
flight_num <- read_csv("Final Flights Data/Number of Flights(2015-2019).csv") %>% na.omit()
colnames(flight_num) <- tolower(gsub(" ", "_", colnames(flight_num)))
flight_num %>% 
  pivot_longer(cols = "alaska_airlines" : "united_airlines", names_to = "flight", values_to = "number") -> flight_num2

flight_num2 %>% filter(year == 2019) %>% 
  ggplot() +
  geom_line(aes(month, number, color = flight), size = 1)
```
 

```{r message=FALSE, warning=FALSE}
ggplot(flight_num2) +
  geom_line(aes(month, number, frame = year, color = flight)) -> p
ggplotly(p)
```
Southwest airlines have the most airlines over 2015 to 2019, and frontier_airlines is the second. The trend does not change much. 

percent change in flight 



```{r}
# movies %>% group_by(release_year, genre) %>%
#   count() %>% arrange(release_year, desc(n)) %>% 
#   spread(key = genre, value = n, fill = 0) %>% 
#   gather(2:16, key = "genre", value = "n") %>% 
#   arrange(release_year, genre) -> genre_year
# 
# ggplot(genre_year, aes(x = genre, y = n)) +
#   geom_point(aes(frame = release_year, color = genre, size = n)) + 
#   theme(axis.text.x = element_text(angle=65, vjust=0.5), legend.position = "none") -> ppn
# ggplotly(ppn)
```

