---
title: "Visualizations-Eman"
author: "Eman Nagib"
date: "2/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(readxl)
library(tibble)
library(stringr)
library(ggplot2)
library(dplyr)
```

```{r} 
## Airfare Table
airfare_df <- read_excel("Final Flights Data/Airfare(2015-2019).xlsx")

names(airfare_df) <- str_replace_all(tolower(names(airfare_df)), "`","")
names(airfare_df) <- str_replace_all(tolower(names(airfare_df)), " ","_")
names(airfare_df) <- gsub("[()]", "", names(airfare_df))
names(airfare_df) <- gsub("[_$]", "", names(airfare_df))

glimpse(airfare_df)
```

```{r}
## On-time Performance Table
time_performance <- read_csv("Final Flights Data/Airline on-time perform(2015-2019).csv", guess_max = 1000)

names(time_performance) <- str_replace_all(tolower(names(time_performance)), "`","")
names(time_performance) <- str_replace_all(tolower(names(time_performance)), " ","_")
names(time_performance) <- str_replace_all(tolower(names(time_performance)), "-","_")
names(time_performance) <- str_replace_all(tolower(names(time_performance)), "[.]","")
names(time_performance) <- gsub("[()]", "", names(time_performance))
time_performance[time_performance == "N`A"] <- NA

time_performance[,3:21] <- lapply(time_performance[,3:21], as.double)

glimpse(time_performance)
```

```{r}
## Delay Reasons Table
delay_reasons <- read_csv("Final Flights Data/Delay Reasons by airline(2015-2019).csv", skip = 1)

delay_reasons$X11 <- NULL

names(delay_reasons) <- str_replace_all(tolower(names(delay_reasons)), "`","")
names(delay_reasons) <- str_replace_all(tolower(names(delay_reasons)), " ","_")
names(delay_reasons) <- str_replace_all(tolower(names(delay_reasons)), "-","")
names(delay_reasons) <- gsub("[()]", "", names(delay_reasons))
delay_reasons[delay_reasons == "N/A"] <- NA
delay_reasons[,3:10] <- lapply(delay_reasons[,3:10], as.double)

glimpse(delay_reasons)
```

```{r}
## Load Factor Table
loadfct_df <- read_csv("Final Flights Data/Load Factor by Airline(2015-2019).csv")

names(loadfct_df) <- str_replace_all(tolower(names(loadfct_df)), "`","")
names(loadfct_df) <- str_replace_all(tolower(names(loadfct_df)), " ","_")

glimpse(loadfct_df)
```

```{r}
## No. Flights Table
no_flights <- read_csv("Final Flights Data/Number of Flights(2015-2019).csv")

names(no_flights) <- str_replace_all(tolower(names(no_flights)), "`","")
names(no_flights) <- str_replace_all(tolower(names(no_flights)), " ","_")

no_flights <- na.omit(no_flights)

glimpse(no_flights)
```

```{r}
## No. Passengers Table
no_passengers <- read_csv("Final Flights Data/Number of Passengers by Airline(2015-2019).csv")

names(no_passengers) <- str_replace_all(tolower(names(no_passengers)), "`","")
names(no_passengers) <- str_replace_all(tolower(names(no_passengers)), " ","_")

glimpse(no_passengers)
```

```{r}
## Cancellation Fees
cancel_fees <- read_csv("Final Flights Data/Res Cxl Fees(2015-2019).csv")

names(cancel_fees) <- str_replace_all(tolower(names(cancel_fees)), "`","")
names(cancel_fees) <- str_replace_all(tolower(names(cancel_fees)), " ","_")
cancel_fees[cancel_fees == "N/A"] <- NA
cancel_fees[,3:15] <- lapply(cancel_fees[,3:15], as.double)

dim(cancel_fees)
glimpse(cancel_fees)
```

```{r fig.height= 10}
airports_by_state <- airfare_df %>% group_by(statename) %>% summarise(count = n(), avg_fare = mean(averagefare))
ggplot(airports_by_state) +
  geom_col(aes(reorder(statename, count), count, fill = avg_fare))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  coord_flip()
```


```{r}
avg_fare_df <- airfare_df %>% group_by(year) %>% summarise(avg_fare = mean(averagefare), count = n())

ggplot(avg_fare_df, aes(year, avg_fare, fill = count)) +
         geom_col()
```
```{r}
airports_by_city <- airfare_df %>% group_by(cityname) %>% 
  summarise(count = n(), avg_fare = mean(averagefare)) %>% arrange(desc(count), desc(avg_fare))
airp_by_city <- airports_by_city[1:35,]

ggplot(airp_by_city) +
  geom_col(aes(reorder(cityname, count), count, fill = avg_fare))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  coord_flip()
```

```{r fig.width= 10}
time_per_year <- time_performance %>% group_by(year) %>% 
  summarise(total_flights = sum(total_number, na.rm = T),
            total_flights_cancelled = sum(total_number_cancelled, na.rm = T),
            total_flights_diverted = sum(total_number_diverted, na.rm = T),
            avg_dep_delay = mean(`average_departure_delay_(minutes)`, na.rm = T),
            avg_taxi_out_time = mean(`average_taxi-out_time_(minutes)`, na.rm = T),
            avg_arr_delay = mean(`average_arrival_delay_(minutes)`, na.rm = T),
            weather_avg_delay = mean(`weather(avg._mins)`, na.rm = T),
            national_aviation_system_avg_delay = mean(`national_aviation_system(avg._mins)`, na.rm = T),
            security_avg_delay = mean(`security(avg._mins)`, na.rm = T),
            late_aircraft_arrival_avg_delay = mean(`late_aircraft_arrival(avg._mins)`, na.rm = T))

ggplot(time_per_year,aes(year, total_flights, fill = total_flights_cancelled))+
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

names(time_pe)
```


```{r fig.width= 10}
p1 <- ggplot(time_per_year,aes(year, total_flights, fill = weather_avg_delay))+
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p2 <- ggplot(time_per_year,aes(year, total_flights, fill = national_aviation_system_avg_delay))+
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p3 <- ggplot(time_per_year,aes(year, total_flights, fill = security_avg_delay))+
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
p4 <- ggplot(time_per_year,aes(year, total_flights, fill = late_aircraft_arrival_avg_delay))+
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
gridExtra::grid.arrange(p1, p2, p3, p4, nrow = 2)
```

```{r fig.width=12, fig.height= 8}
time_per_airlines <- time_performance %>% group_by(carriers) %>% 
  summarise(total_flights = sum(total_number, na.rm = T),
            total_flights_cancelled = sum(total_number_cancelled, na.rm = T),
            total_flights_diverted = sum(total_number_diverted, na.rm = T),
            avg_dep_delay = mean(`average_departure_delay_(minutes)`, na.rm = T),
            avg_taxi_out_time = mean(`average_taxi-out_time_(minutes)`, na.rm = T),
            avg_arr_delay = mean(`average_arrival_delay_(minutes)`, na.rm = T),
            weather_avg_delay = mean(`weather(avg._mins)`, na.rm = T),
            national_aviation_system_avg_delay = mean(`national_aviation_system(avg._mins)`, na.rm = T),
            security_avg_delay = mean(`security(avg._mins)`, na.rm = T),
            late_aircraft_arrival_avg_delay = mean(`late_aircraft_arrival(avg._mins)`, na.rm = T))

p5 <- ggplot(time_per_airlines,aes(reorder(carriers,-weather_avg_delay), weather_avg_delay))+
  geom_col(fill = "dark blue") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p6 <- ggplot(time_per_airlines,aes(reorder(carriers, -national_aviation_system_avg_delay), national_aviation_system_avg_delay))+
  geom_col(fill = "dark green") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_brewer(palette="Dark2")

p7 <- ggplot(time_per_airlines,aes(reorder(carriers, -security_avg_delay),security_avg_delay))+
  geom_col(fill = "purple") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_brewer(palette="Dark2")

p8 <- ggplot(time_per_airlines,aes(reorder(carriers, -late_aircraft_arrival_avg_delay), late_aircraft_arrival_avg_delay))+
  geom_col(fill = "maroon") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_brewer(palette="Dark2")

gridExtra::grid.arrange(p5, p6, p7, p8, nrow = 2)
```

```{r}
ggplot(time_per_airlines,aes(reorder(carriers,-avg_dep_delay), avg_dep_delay))+
  geom_col(fill = "purple") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
ggplot(time_per_airlines,aes(reorder(carriers,-total_flights), total_flights, fill = total_flights_diverted))+
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r fig.width= 8}
lf_by_month <- loadfct_df %>% group_by(month) %>% summarise(alaska_airlines_avg = mean(alaska_airlines),
                                             allegiant_airlines_avg = mean(allegiant_airlines),
                                             american_airlines_avg = mean(american_airlines),
                                             delta_airlines_avg = mean(delta_airlines),
                                             frontier_airlines_avg = mean(frontier_airlines),
                                             hawaiian_airlines_avg = mean(hawaiian_airlines),
                                             jetblue_airlines_avg = mean(jetblue_airlines),
                                             southwest_airlines_avg = mean(southwest_airlines),
                                             spirit_airlines_avg = mean(spirit_airlines),
                                             united_airlines_avg = mean(united_airlines))
                                             
                                        
ggplot(lf_by_month)+
  geom_line(aes(month,alaska_airlines_avg))+
  geom_line(aes(month,allegiant_airlines_avg), col = "cornflowerblue") +
  geom_line(aes(month,american_airlines_avg), col = "coral4") +
  geom_line(aes(month,delta_airlines_avg), col = "greenyellow") +
  geom_line(aes(month,frontier_airlines_avg), col = "deeppink4") +
  geom_line(aes(month,hawaiian_airlines_avg), col = "darkseagreen4") +
  geom_line(aes(month,jetblue_airlines_avg), col = "brown4") +
  geom_line(aes(month,southwest_airlines_avg), col = "darkorchid4") +
  geom_line(aes(month,spirit_airlines_avg), col = "orange4") +
  geom_line(aes(month,united_airlines_avg), col = "olivedrab")+
  scale_x_continuous(breaks=seq(1, 12, 1))

```

```{r fig.width= 10, fig.height=10}
canc_fees_by_quarter <- cancel_fees %>% group_by(quarter) %>% summarise(alaska_avg = mean(alaska, na.rm = T),
                                             allegiant_avg = mean(allegiant , na.rm = T),
                                             american_avg = mean(american , na.rm = T),
                                             delta_avg = mean(delta, na.rm = T),
                                             frontier_avg = mean(frontier, na.rm = T),
                                             hawaiian_avg = mean(hawaiian, na.rm = T),
                                             jetblue_avg = mean(jetblue, na.rm = T),
                                             virgin_america_avg = mean(virgin_america, na.rm = T),
                                             spirit_avg = mean(spirit, na.rm = T),
                                             united_avg = mean(united, na.rm = T),
                                             sun_country_avg = mean(sun_country, na.rm = T),
                                             island_air_hawaii_avg = mean(us_airways, na.rm = T),
                                             us_airways_avg = mean(us_airways, na.rm = T))
                                             
                                        
q1 <- ggplot(canc_fees_by_quarter)+
  geom_col(aes(quarter,alaska_avg))

q2 <- ggplot(canc_fees_by_quarter)+
  geom_col(aes(quarter,allegiant_avg), fill = "cornflowerblue") 

q3 <- ggplot(canc_fees_by_quarter)+    
  geom_col(aes(quarter,american_avg), fill = "coral4") 

q4 <- ggplot(canc_fees_by_quarter)+
  geom_col(aes(quarter,delta_avg), fill = "greenyellow") 

q5 <- ggplot(canc_fees_by_quarter)+
  geom_col(aes(quarter,frontier_avg), fill = "deeppink4") 

q6 <- ggplot(canc_fees_by_quarter)+
  geom_col(aes(quarter,hawaiian_avg), fill = "darkseagreen4") 

q7 <- ggplot(canc_fees_by_quarter)+
  geom_col(aes(quarter,jetblue_avg), fill = "brown4") 

q8 <- ggplot(canc_fees_by_quarter)+
  geom_col(aes(quarter,virgin_america_avg), fill = "darkorchid4") 

q9 <- ggplot(canc_fees_by_quarter)+
  geom_col(aes(quarter,spirit_avg), fill = "orange4") 

q10 <- ggplot(canc_fees_by_quarter)+
  geom_col(aes(quarter,united_avg), fill = "olivedrab")
  
q11 <- ggplot(canc_fees_by_quarter)+  
  geom_col(aes(quarter,sun_country_avg), fill = "red")
  
q12 <- ggplot(canc_fees_by_quarter)+  
  geom_col(aes(quarter,island_air_hawaii_avg), fill = "blue")
  
q13 <- ggplot(canc_fees_by_quarter)+  
    geom_col(aes(quarter,us_airways_avg), fill = "pink")

gridExtra::grid.arrange(q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, q11, q12, nrow=4)
```

